export interface MultiQuantity {
  shopee?: number;
  lazada?: number;
  tiki?: number;
  tiktok?: number;
}

/**
 * Configuration used to initialize `ShopeeModule`.
 *
 * Typical shop-level usage:
 *
 * ```ts
 * const shopee = new ShopeeModule({
 *   partnerId: 123456,
 *   partnerKey: 'YOUR_PARTNER_KEY',
 *   shopId: 'YOUR_SHOP_ID',
 *   accessToken: 'YOUR_ACCESS_TOKEN',
 *   refreshToken: 'YOUR_REFRESH_TOKEN',
 * });
 * ```
 *
 * Token exchange usage after callback:
 *
 * ```ts
 * const shopee = new ShopeeModule({
 *   partnerId: 123456,
 *   partnerKey: 'YOUR_PARTNER_KEY',
 *   shopId: 'YOUR_SHOP_ID',
 * });
 * ```
 *
 * Main-account authorization usage:
 *
 * ```ts
 * const shopee = new ShopeeModule({
 *   partnerId: 123456,
 *   partnerKey: 'YOUR_PARTNER_KEY',
 *   mainAccountId: 'YOUR_MAIN_ACCOUNT_ID',
 * });
 * ```
 */
export interface ShopeeConfig {
  /**
   * Shopee partner ID from Shopee Open Platform.
   * Required for all API calls and auth flows.
   */
  partnerId: number;
  /**
   * Shopee partner key used to sign requests with HMAC-SHA256.
   * Keep this on the server only.
   */
  partnerKey: string;
  /**
   * Shopee shop ID.
   * Required for shop-level private APIs and shop-level token refresh.
   * For `fetchToken()`, provide either `shopId` or `mainAccountId`, not both.
   */
  shopId?: string;
  /**
   * Shopee main account ID returned from the authorization callback.
   * Use this for main-account authorization flows when exchanging the auth code.
   * For `fetchToken()`, provide either `shopId` or `mainAccountId`, not both.
   */
  mainAccountId?: string;
  /**
   * Current Shopee access token.
   * Required for private APIs such as orders, products, logistics, and payment APIs.
   */
  accessToken?: string;
  /**
   * Current Shopee refresh token.
   * Required when calling `refreshToken()`.
   */
  refreshToken?: string;
  /**
   * Optional token expiry timestamp kept by the application.
   */
  tokenExpired?: string;
  /**
   * Optional access token lifetime in seconds.
   */
  expireIn?: number;
  /**
   * Optional refresh token lifetime in seconds.
   */
  refreshTokenExpireIn?: number;
}

export interface ShopeeConfigList {
  [shopId: string]: ShopeeConfig;
}

export interface ShopeeRequestCommon {
  sign?: string; //Signature generated by partner_id, api path, timestamp, access_token, shop_id and partner_key via HMAC-SHA256 hashing algorithm.
  partner_id?: number; //The partner_id obtained from the App. This partner_id is put into the query
  timestamp?: number; //	Timestamp, valid for 5 minutes.
  access_token?: string; //The token for API access, using to identify your permission to the api. Valid for multiple use and expires in 4 hours.
  shop_id?: number; //Shopee's unique identifier for a shop. Required param for most APIs.
}

export interface ShopeeRequestGetAccesstoken {
  code: string; //the return from the generateAuthURL includes auth_code.
  partner_id: number;
  shop_id?: number;
  main_account_id?: number;
  sign?: string; //generate manual
  timestamp?: number; //generate manual
}

export interface ShopeeRequestRefreshToken {
  refresh_token: string; //Each refresh_token is valid for 30 days,
  partner_id: number;
  shop_id: number;
  sign?: string;
  timestamp?: number; //	Timestamp, valid for 5 minutes.
}
